name: Android Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-report
        path: app/build/reports/tests/testDebugUnitTest/
